// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "idserver.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



MiLissa::IdServer_ptr MiLissa::IdServer_Helper::_nil() {
  return ::MiLissa::IdServer::_nil();
}

::CORBA::Boolean MiLissa::IdServer_Helper::is_nil(::MiLissa::IdServer_ptr p) {
  return ::CORBA::is_nil(p);

}

void MiLissa::IdServer_Helper::release(::MiLissa::IdServer_ptr p) {
  ::CORBA::release(p);
}

void MiLissa::IdServer_Helper::marshalObjRef(::MiLissa::IdServer_ptr obj, cdrStream& s) {
  ::MiLissa::IdServer::_marshalObjRef(obj, s);
}

MiLissa::IdServer_ptr MiLissa::IdServer_Helper::unmarshalObjRef(cdrStream& s) {
  return ::MiLissa::IdServer::_unmarshalObjRef(s);
}

void MiLissa::IdServer_Helper::duplicate(::MiLissa::IdServer_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

MiLissa::IdServer_ptr
MiLissa::IdServer::_duplicate(::MiLissa::IdServer_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

MiLissa::IdServer_ptr
MiLissa::IdServer::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


MiLissa::IdServer_ptr
MiLissa::IdServer::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

MiLissa::IdServer_ptr
MiLissa::IdServer::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_IdServer _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_IdServer* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_IdServer;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* MiLissa::IdServer::_PD_repoId = "IDL:MiLissa/IdServer:1.0";


MiLissa::_objref_IdServer::~_objref_IdServer() {
  
}


MiLissa::_objref_IdServer::_objref_IdServer(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::MiLissa::IdServer::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
MiLissa::_objref_IdServer::_ptrToObjRef(const char* id)
{
  if( id == ::MiLissa::IdServer::_PD_repoId )
    return (::MiLissa::IdServer_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::MiLissa::IdServer::_PD_repoId) )
    return (::MiLissa::IdServer_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cstring_i_cstring
class _0RL_cd_aa18c0ff3724c47b_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_aa18c0ff3724c47b_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var result;
};

void _0RL_cd_aa18c0ff3724c47b_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_aa18c0ff3724c47b_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_aa18c0ff3724c47b_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalString(result,0);

}

void _0RL_cd_aa18c0ff3724c47b_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalString(0);

}

const char* const _0RL_cd_aa18c0ff3724c47b_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_aa18c0ff3724c47b_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_aa18c0ff3724c47b_00000000* tcd = (_0RL_cd_aa18c0ff3724c47b_00000000*)cd;
  MiLissa::_impl_IdServer* impl = (MiLissa::_impl_IdServer*) svnt->_ptrToInterface(MiLissa::IdServer::_PD_repoId);
  tcd->result = impl->generateId(tcd->arg_0);


}

char* MiLissa::_objref_IdServer::generateId(const char* fileName)
{
  _0RL_cd_aa18c0ff3724c47b_00000000 _call_desc(_0RL_lcfn_aa18c0ff3724c47b_10000000, "generateId", 11);
  _call_desc.arg_0 = fileName;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring
class _0RL_cd_aa18c0ff3724c47b_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_aa18c0ff3724c47b_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_aa18c0ff3724c47b_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_aa18c0ff3724c47b_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

void _0RL_cd_aa18c0ff3724c47b_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_aa18c0ff3724c47b_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_aa18c0ff3724c47b_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_aa18c0ff3724c47b_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_aa18c0ff3724c47b_20000000* tcd = (_0RL_cd_aa18c0ff3724c47b_20000000*)cd;
  MiLissa::_impl_IdServer* impl = (MiLissa::_impl_IdServer*) svnt->_ptrToInterface(MiLissa::IdServer::_PD_repoId);
  tcd->result = impl->verifyId(tcd->arg_0);


}

::CORBA::Boolean MiLissa::_objref_IdServer::verifyId(const char* id)
{
  _0RL_cd_aa18c0ff3724c47b_20000000 _call_desc(_0RL_lcfn_aa18c0ff3724c47b_30000000, "verifyId", 9);
  _call_desc.arg_0 = id;

  _invoke(_call_desc);
  return _call_desc.result;


}
MiLissa::_pof_IdServer::~_pof_IdServer() {}


omniObjRef*
MiLissa::_pof_IdServer::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::MiLissa::_objref_IdServer(ior, id);
}


::CORBA::Boolean
MiLissa::_pof_IdServer::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::MiLissa::IdServer::_PD_repoId) )
    return 1;
  
  return 0;
}

const MiLissa::_pof_IdServer _the_pof_MiLissa_mIdServer;

MiLissa::_impl_IdServer::~_impl_IdServer() {}


::CORBA::Boolean
MiLissa::_impl_IdServer::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "generateId") ) {

    _0RL_cd_aa18c0ff3724c47b_00000000 _call_desc(_0RL_lcfn_aa18c0ff3724c47b_10000000, "generateId", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "verifyId") ) {

    _0RL_cd_aa18c0ff3724c47b_20000000 _call_desc(_0RL_lcfn_aa18c0ff3724c47b_30000000, "verifyId", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
MiLissa::_impl_IdServer::_ptrToInterface(const char* id)
{
  if( id == ::MiLissa::IdServer::_PD_repoId )
    return (::MiLissa::_impl_IdServer*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::MiLissa::IdServer::_PD_repoId) )
    return (::MiLissa::_impl_IdServer*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
MiLissa::_impl_IdServer::_mostDerivedRepoId()
{
  return ::MiLissa::IdServer::_PD_repoId;
}

POA_MiLissa::IdServer::~IdServer() {}

