package MiLissa;


/**
* MiLissa/IdServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Tuesday, January 22, 2013 10:56:45 PM BRST
*/

public interface IdServerOperations 
{
  String generateId (String fileName);
  boolean verifyId (String id);
} // interface IdServerOperations
