package MiLissa;


/**
* MiLissa/IdServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Tuesday, January 22, 2013 10:56:45 PM BRST
*/

abstract public class IdServerHelper
{
  private static String  _id = "IDL:MiLissa/IdServer:1.0";

  public static void insert (org.omg.CORBA.Any a, MiLissa.IdServer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MiLissa.IdServer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MiLissa.IdServerHelper.id (), "IdServer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MiLissa.IdServer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IdServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MiLissa.IdServer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MiLissa.IdServer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MiLissa.IdServer)
      return (MiLissa.IdServer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MiLissa._IdServerStub stub = new MiLissa._IdServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MiLissa.IdServer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MiLissa.IdServer)
      return (MiLissa.IdServer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MiLissa._IdServerStub stub = new MiLissa._IdServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
