package MiLissa;


/**
* MiLissa/IdServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Monday, January 28, 2013 9:23:03 AM BRST
*/

public interface IdServerOperations 
{
  String generateId (String fileName);
  boolean verifyId (String id);
} // interface IdServerOperations
