package MiLissa;


/**
* MiLissa/IdServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Monday, January 28, 2013 9:23:03 AM BRST
*/

public interface IdServer extends IdServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdServer
