package MiLissa;


/**
* MiLissa/IdServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idserver.idl
* Tuesday, January 22, 2013 10:56:45 PM BRST
*/

public interface IdServer extends IdServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IdServer
